config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  resources :random_strings
  
  get 'static_pages/home'            

  get 'static_pages/about'           

  get 'static_pages/help'            

  get 'static_pages/contact'         

  get 'random_strings/new'

  get 'random_strings/index'
  
  get 'home'            =>  'static_pages#home'

  get 'about'           =>  'static_pages#about'

  get 'help'            =>  'static_pages#help'

  get 'contact'         =>  'static_pages#contact'

end

app/models/random_string.rb
class RandomString < ActiveRecord::Base
  
  def self.to_csv
    CSV.generate do |csv|
      csv << ['Random Value', 'Date Generated']
      
      all.each do |random_string|
        csv << [random_string.random_value, random_string.created_at]
      end
    end
  end
  
  def self.to_xls
    p = Axlsx::Package.new
    p.workbook.add_worksheet(name: 'Random Values') do |sheet|
      sheet.add_row ["Random Value", "Date Generated"]
      
      all.each do |random_string|
        sheet.add_row [random_string.random_value, random_string.created_at]
      end
    end
    
    p.serialize('tmp/random.xls')
    'tmp/random.xls'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/random_strings_controller.rb
class RandomStringsController < ApplicationController
  def new
    @random_string = RandomString.new
  end
  
  def create
#     params = params.permit(:maximum, :minimum, :prefix)
    maximum = params[:maximum] ? params[:maximum].to_i : 1000000000000
    minimum = params[:minimum] ? params[:minimum].to_i : 0
    prefix = params[:prefix] ? params[:prefix] : ""
    random_value = Random.new.rand( maximum - minimum) + minimum
    @random_string = RandomString.new(random_value: prefix + random_value.to_s)
    
    if @random_string.save
      redirect_to @random_string
    else
      flash.now[:danger] = "Whoopsie daisy. Random number generation failed for some reason!"
      render 'new'
    end
  end

  def index
    @random_strings = RandomString.order(created_at: :desc).page params[:page]
    
    respond_to do |format|
      format.html
      format.csv  { render text: @random_strings.to_csv }
      format.xls  { send_file @random_strings.to_xls }
    end
  end
  
  def show
    @random_string = RandomString.find_by_id(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/random_strings_helper.rb
module RandomStringsHelper
#   @default_maximum = 1000000000000000
  
#   attr_reader :default_minimum
#   attr_reader :default_maximum
#   @default_minimum = 0
  def default_minimum
    0
  end
  
  def default_maximum
    1000000000000000
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stokastik</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Stokastik</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/home">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="../navbar/">Default</a></li>
            <li><a href="../navbar-static-top/">Static top</a></li>
            <li class="active"><a href="./">Fixed top <span class="sr-only">(current)</span></a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

  
  
<%= yield %>

  <footer class="footer">
      <div class="container">
        <p class="text-muted">Stokastik</p>
        <p class="pull-right text-muted">&copy; st3v0</p>
      </div>
    </footer>

  
</body>
</html>

app/views/random_strings/index.html.erb
<div class="container">
  <table class="table table-striped table-hover">
    <tr>
      <td>
      </td>
      <th>
        <span class="pull-right">
          Export
          <span class="glyphicon glyphicon-export"></span>
        </span>
      </th>
      <td>
        <span class="pull-right">
        <%= link_to 'CSV', random_strings_path + '.csv', class: 'btn btn-default btn-lg' %>
        <%= link_to 'Excel', random_strings_path + '.xls', class: 'btn btn-default btn-lg' %>
        </span>
      <td>
    </tr>
    <tr>
      <th><%= check_box_tag 'select_all_random_strings', 'all'%></th>
      <th>Random Number</th>
      <th>Generated</th>
    </tr>
    
    <% @random_strings.each do |random_string| %>
      <tr>
        <td><%= check_box_tag 'random_string_ids[]', random_string.id %></td>
        <td><%= random_string.random_value %></td>
        <td><%= time_tag random_string.created_at %></td>
    </tr>
    <% end %>
    
    <%= paginate @random_strings %>
  </table>
</div>

app/views/random_strings/new.html.erb
<div class="container">
  <div class="jumbotron">
    <h2>Generate a random number</h2>
  </div>
  
  <%= form_for @random_string, html: {class: 'form-inline'} do |f| %>

  <%= label_tag 'batch', 'Batch Mode' %>
    <%= check_box_tag 'batch' %>

  <div class="input-group col-md-2">
    <%= number_field_tag 'quantity', '2', min: '2', max: '1000', class: 'form-control' %>
    <span class="input-group-addon">Numbers</span>
  </div>
  
  <div class="input-group col-md-2">
    <span class="input-group-addon"> Between </span>
    <%= number_field_tag 'minimum', default_minimum.to_s, class: 'form-control' %>
  </div>
  <div class="input-group col-md-2">
    <span class="input-group-addon">and</span> 
    <%= number_field_tag 'maximum', default_maximum.to_s, class: 'form-control' %>
  </div>
  
 <div class="input-group col-md-2">
   <span class="input-group-addon">Prefix</span>
    <%= text_field_tag 'prefix', nil, placeholder: 'Optional prefix...', class: 'form-control' %>
  </div>
  
   <%= f.submit 'Generate!', class: 'btn btn-default btn-lg'%>
  <% end %>
</div>

app/views/random_strings/show.html.erb
<div class="container">
  <div class="jumbotron">
    <h1><%= @random_string.random_value %></h1>
    <%= link_to 'Generate another one', new_random_string_path, class: 'btn btn-default btn-lg' %>
  </div>
</div>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="container">
  <div class="jumbotron">
    <h3>Welcome  to</h3>
    <h1>Stokastik</h1>
    <h3>A random number generation service</h3>
    
    <%= link_to 'Generate a random number', new_random_string_path, class: 'btn btn-default btn-lg' %>
    <%= link_to 'View already generated random numbers', random_strings_path, class: 'btn btn-default btn-lg' %>
  </div>
</div>